### ISSUE TITLE
Problem with Int64 dtype of pandas

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audmetric#17]
This works as expected:

```python
import audmetric

truth = pd.Series([30, 40, 50])
prediction = pd.Series([32, 38, 55])
audmetric.pearson_cc(truth, prediction)
```
```
0.9639278544917691
```

but when we convert the series to `Int64`, it fails:

```python
truth = truth.astype(pd.Int64Dtype)
prediction = prediction.astype(pd.Int64Dtype)
audmetric.pearson_cc(truth, prediction)
```
```
Traceback (most recent call last):
  File "/media/jwagner/Data/Git/pyaudmetric/my/my.py", line 13, in <module>
    y = audmetric.pearson_cc(truth, prediction)
  File "/media/jwagner/Data/Git/pyaudmetric/audmetric/core/api.py", line 675, in pearson_cc
    return float(np.corrcoef(prediction, truth)[0][1])
  File "<__array_function__ internals>", line 6, in corrcoef
  File "/media/jwagner/Data/Git/pyaudmetric/venv/lib/python3.6/site-packages/numpy/lib/function_base.py", line 2551, in corrcoef
    c = cov(x, y, rowvar)
  File "<__array_function__ internals>", line 6, in cov
  File "/media/jwagner/Data/Git/pyaudmetric/venv/lib/python3.6/site-packages/numpy/lib/function_base.py", line 2456, in cov
    avg, w_sum = average(X, axis=1, weights=w, returned=True)
  File "<__array_function__ internals>", line 6, in average
  File "/media/jwagner/Data/Git/pyaudmetric/venv/lib/python3.6/site-packages/numpy/lib/function_base.py", line 415, in average
    if scl.shape != avg.shape:
AttributeError: 'float' object has no attribute 'shape'
```

The error message is not very helpful, but the problem is basically that `numpy` converts `Int64` to type `object`:

```python
truth = np.array(truth)  # convert series to array
truth.dtype
```
```
object
```

**Comment by frankenjoe** [comment]
An easy way to fix this (probably not the most efficient solution) is by not converting directly from `pd.Series` to a numpy array, but convert first do a list. E.g. this works:

```python
truth = truth.astype('Int64')
prediction = prediction.astype('Int64')

truth = np.array(list(truth))
prediction = np.array(list(prediction))

audmetric.pearson_cc(truth, prediction)
```
```
0.9639278544917691
```
